### ISSUE TITLE
CAB not restored on rotation in demo

### ISSUE THREAD

**Issue by plusCubed** [afollestad/material-cab#1]
I'm not sure if this is the library's fault, but I couldn't get the CAB working in Cabinet after rotation (Perhaps I should open an issue there?). 
Either way, the demo code here doesn't restore the CAB after rotation, and it's going to be important that people implement the restoration properly.

Or, if you have any ideas on making it just restore automatically (like the stock CAB), that'd be even better. I'm not sure that's possible though.

**Comment by afollestad** [comment]
Oh right, I forgot to implement that. It's basically the same as how the bread crumb layout works, the local fields can survive through orientation change since `MaterialCab` is `Serializable`, it just needs to re-initialize everything during restoration.

**Comment by afollestad** [comment]
The stock CAB hooks into Activity events since it's part of the framework obviously, all that we can really do is manually invoke methods to save/restore the state.

**Comment by afollestad** [comment]
It should in theory work but for some reason the CAB toolbar isn't actually visible after restoration (even though the visibility is indeed being set and everything is reinitialized).

**Comment by afollestad** [comment]
Fixed
