### ISSUE TITLE
How to use in a fragment

### ISSUE THREAD

**Issue by prakashraman** [afollestad/material-cab#10]
I would like to insert this material cab in a Fragment

MaterialCab cab = new MaterialCab(getActivity(), R.id.cab_stub) gives the error

required: AppCompatActivity,int
  found: FragmentActivity,int
  reason: actual argument FragmentActivity cannot be converted to AppCompatActivity by method invocation conversion

How can  I fix this ?

**Comment by afollestad** [comment]
Cast `getActivity()` to the name of your Activity.
