### ISSUE TITLE
How do I use it if I am using View.OnClickListener within ViewHolder?

### ISSUE THREAD

**Issue by salvator91** [afollestad/material-cab#13]
In your examples View.OnClickListener is within adapter. But I am using View OnClickListener with Viewolder that is in a separate file. Further I am using fragments within ViewPager and eac of these fragments contain recyclerview. 

Please give a simple outline of how to proceed before you close this issue, as this is not exactly an issue but a question.

**Comment by afollestad** [comment]
You should never do that. 

A callback should be sent to your Activity from which you show the dialog.

**Comment by salvator91** [comment]
Please elaborate a bit. What is that I shouldn't do? If possible give an outline of code.
