### ISSUE TITLE
The Lib minimum version on gradle is 14?

### ISSUE THREAD

**Issue by ankitagrawal2411** [afollestad/material-cab#18]
I see the lib has a minimum requirement of api level 14
But I don't see any code that needs api level 14 , why not provide support for api 10.
Also is there any code that needs api 14 ?

**Comment by Jawnnypoo** [comment]
Sometimes devs choose not to support < 14 since it is mostly obsolete, and in case something did come up that is not 14+, they not have to worry about it.
