### ISSUE TITLE
Change back icon and text color

### ISSUE THREAD

**Issue by BlueMango92** [afollestad/material-cab#19]
First of all great library!

If I use a white background the back icon and the title become invisible because their default color is also white. Can I change their color?

Thanks!

**Comment by dsharew** [comment]
Hey I found this hack to change text and icon color on white background:
```

 materialCab.getToolbar().setTitleTextColor(getResources().getColor(R.color.black));
            VectorDrawableCompat indicator = VectorDrawableCompat.create(getResources(), R.drawable.ic_arrow_back_black_24dp, getTheme());
            indicator.setTint(ResourcesCompat.getColor(getResources(), R.color.black, getTheme()));
            materialCab.getToolbar().setNavigationIcon(indicator);
```

But the issue with is is the action bar does not have border bottom.

I will be happy if anyone can help me on how to add border bottom to the action bar.

**Comment by afollestad** [comment]
This _shouldn't_ happen with newer versions of the lib.
