### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by EricSocrates** [afollestad/material-cab#25]
1.When I test this code in my OnePlus 3, I meet jam issue.
```java
MaterialCab mCab = new MaterialCab(activity, R.id.cab_stub_storage).setMenu(R.menu.menu_storage_cab).start(activity);
```

2. I downloaded V1.3.0 in two two ways: via gradle and download the .aar zip to local, but I meet the same issue:

Unresolved dependencies
(My project path)	
app/build.gradle	
Failed to resolve: :material-cab-1.3.0.aar:`<a href="openFile:X:/Android/StorageLogistics/app/build.gradle">Open File</a>`

**Comment by EricSocrates** [comment]
I use my poor English and look forward master's reply, thx!!

**Comment by afollestad** [comment]
1) I have no idea what you're talking about

2) You may be missing a repository declaration

**Comment by EricSocrates** [comment]
Well, i will check my code again, thank you!
