### ISSUE TITLE
Multiple locations in an Activity don't work as expected

### ISSUE THREAD

**Issue by svenoaks** [afollestad/material-cab#29]
**Library Version:**

1.3.1
 
**Affected Device(s):**
 
All
 
**Describe the Bug:**

Attaching to more than one view in an Activity sequentially causes Material Cab to attach to the first one, even if view id of the next is specified.

**To Reproduce:**
1. Add a Fragment to an Activity with a ViewStub or ViewGroup and specify that View when attaching Cab
2.  Add another fragment with a ViewStub or ViewGroup with a different id than the first and attach to that View.
3. Material Cab appears in same location as step 1.

**Expected Behavior:**

The Cab attaches to the first View, then the second.

This caused because library sets `R.id.mcab_toolbar` View to `View.GONE` and it will find this View again when attaching to the second.

I worked around it at application level but I think library should be able to handle this.

**Comment by afollestad** [comment]
2.0.0 should resolve this
