### ISSUE TITLE
Support for AppBarLayout

### ISSUE THREAD

**Issue by vanniktech** [afollestad/material-cab#3]
Is there an example on how to use the CAB when using [AppBarLayout](https://developer.android.com/reference/android/support/design/widget/AppBarLayout.html)? Since AppBarLayout is a LinearLayout and not a frame layout the positioning and some other things don't work as expected.

It would also be interesting to know if the CAB can be used in conjunction with the [TabLayout](https://developer.android.com/reference/android/support/design/widget/TabLayout.html).

**Comment by Rainer-Lang** [comment]
+1 for both

**Comment by adnbsr** [comment]
Hide/Show actionbar works for me on Callback in case of AppBarLayout.

**Comment by vanniktech** [comment]
I also found a way to get it working. My XML looks like this:

```xml
<android.support.design.widget.AppBarLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

    <android.support.v7.widget.Toolbar
        android:id="@+id/activity_main_toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        app:layout_scrollFlags="scroll|enterAlways"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light"/>

    <ViewStub
        android:id="@+id/cab_stub"
        android:layout_width="match_parent"
        android:layout_height="?actionBarSize"/>

    <android.support.design.widget.TabLayout
        android:id="@+id/activity_main_tabs"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>

</android.support.design.widget.AppBarLayout>
```

And then I just hide / show the Cab whenever I want to and it overlays over the Toolbar.
