### ISSUE TITLE
MaterialCab with ViewPager

### ISSUE THREAD

**Issue by guger** [afollestad/material-cab#31]
I'm using MaterialCab with ViewPager..

Using v1.3.8, I checked for `MaterialCab.isActive` in every `onPageChanged` of the ViewPager, to hide the CAB if its shown. Since MaterialCab was static, this was easy. The problem is, that the ViewPager (callback) and the MaterialCab initializer are not in the same fragment.. 

So is there a possibility since v2, to get a shown MaterialCab by its id and destroy it from another fragment?

**Comment by afollestad** [comment]
Ideally you should be keeping a reference to the instance returned by `createCab(...)` - a find by ID mechanism would require a static map which I'd prefer to avoid

**Comment by guger** [comment]
I'm keeping an instance, but unfortunately, the `onBackPressed` event, for example, is only called in an activity, but my cab reference is stored in a child fragment held by a viewpager.

So now, I need an event-bus to close the cab from my activities `onBackPressed`.

**Comment by afollestad** [comment]
You could always store the instance in your `Activity` and access it via `getActivity()` in your `Fragment`'s

**Comment by afollestad** [comment]
Your Fragments could extend a base class that make it more convenient to get the instance without duplicating the casting, ect.
