### ISSUE TITLE
title typeface and gravity?

### ISSUE THREAD

**Issue by TheLoyalCruel** [afollestad/material-cab#6]
how to change the title typeface (font)? 
and is it possible to change the gravity for RTL layouts?
thanks...

**Comment by afollestad** [comment]
The `Toolbar` class doesn't allow you to change typefaces directly. I'm guessing it can be done through title text appearances. RTL layouts are automatic if the device is in RTL mode.

Feel free to submit pull requests if you want. But there isn't much needed for this.
